export const ErrorsMap = {
    // order same as:
    // https://github.com/threefoldtech/tfchain_pallets/blob/f0bb8747d7c70769c77cf814d8f02384b211c88d/pallet-smart-contract/src/lib.rs#L59
    smartContractModule: [
        "TwinNotExists",
        "NodeNotExists",
        "FarmNotExists",
        "FarmHasNotEnoughPublicIPs",
        "FarmHasNotEnoughPublicIPsFree",
        "FailedToReserveIP",
        "FailedToFreeIPs",
        "ContractNotExists",
        "TwinNotAuthorizedToUpdateContract",
        "TwinNotAuthorizedToCancelContract",
        "NodeNotAuthorizedToDeployContract",
        "NodeNotAuthorizedToComputeReport",
        "PricingPolicyNotExists",
        "ContractIsNotUnique",
        "NameExists",
        "NameNotValid",
        "InvalidContractType",
        "TFTPriceValueError",
    ],
    // order same as:
    // https://github.com/threefoldtech/tfchain_pallets/blob/f0bb8747d7c70769c77cf814d8f02384b211c88d/pallet-tfgrid/src/lib.rs#L129
    tfgridModule: [
        "NoneValue",
        "StorageOverflow",
        "CannotCreateNode",
        "NodeNotExists",
        "NodeWithTwinIdExists",
        "CannotDeleteNode",
        "NodeDeleteNotAuthorized",
        "NodeUpdateNotAuthorized",
        "FarmExists",
        "FarmNotExists",
        "CannotCreateFarmWrongTwin",
        "CannotUpdateFarmWrongTwin",
        "CannotDeleteFarm",
        "CannotDeleteFarmWithPublicIPs",
        "CannotDeleteFarmWithNodesAssigned",
        "CannotDeleteFarmWrongTwin",
        "IpExists",
        "IpNotExists",
        "EntityWithNameExists",
        "EntityWithPubkeyExists",
        "EntityNotExists",
        "EntitySignatureDoesNotMatch",
        "EntityWithSignatureAlreadyExists",
        "CannotUpdateEntity",
        "CannotDeleteEntity",
        "SignatureLenghtIsIncorrect",
        "TwinExists",
        "TwinNotExists",
        "TwinWithPubkeyExists",
        "CannotCreateTwin",
        "UnauthorizedToUpdateTwin",
        "PricingPolicyExists",
        "PricingPolicyNotExists",
        "PricingPolicyWithDifferentIdExists",
        "CertificationCodeExists",
        "FarmingPolicyAlreadyExists",
        "FarmPayoutAdressAlreadyRegistered",
        "FarmerDoesNotHaveEnoughFunds",
        "UserDidNotSignTermsAndConditions",
        "FarmerDidNotSignTermsAndConditions",
        "FarmerNotAuthorized",
    ],
    // order same as:
    // https://github.com/threefoldtech/tfchain_pallets/blob/27e82b3e0ca030f40cf63adba6021cc4c359e5c0/pallet-kvstore/src/lib.rs#L43
    tfkvStore: ["NoValueStored", "KeyIsTooLarge", "ValueIsTooLarge"],
};
