# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: grid3-nightly

on:  
  push:
    branches: [ development_nightly ]
  schedule:
    - cron: "0 6 * * *"

jobs:
  deployment-scripts:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git libtool tmux redis net-tools
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: set env variables
        run: |
          echo "NETWORK=dev" >> $GITHUB_ENV
          echo "RMB_PROXY=true" >> $GITHUB_ENV
          echo "STORE_SECRET=secret" >> $GITHUB_ENV
          echo "MNEMONIC=${{ secrets.MNEMONIC }}" >> $GITHUB_ENV
      - name: Run test single vm
        id: singlevm
        continue-on-error: true
        run: |
          yarn run ts-node --project tsconfig-node.json scripts/single_vm.ts
      - name: Run test multiple vms
        id: multiplevm
        continue-on-error: true
        run: |
          yarn run ts-node --project tsconfig-node.json scripts/multiple_vms.ts
      - name: Run test kubernetes
        id: kubernetes
        continue-on-error: true
        run: |
          yarn run ts-node --project tsconfig-node.json scripts/kubernetes.ts
      - name: Run test vm with qsfs
        id: vmqsfs
        continue-on-error: true
        run: |
          yarn run ts-node --project tsconfig-node.json scripts/vm_with_qsfs.ts
      - name: Run test kubernetes with qsfs
        id: kubernetesqsfs
        continue-on-error: true
        run: |
          yarn run ts-node --project tsconfig-node.json scripts/kubernetes_with_qsfs.ts
      - name: Run test dynamic single vm
        id: dynamicsinglevm
        continue-on-error: true
        run: |
          yarn run ts-node --project tsconfig-node.json scripts/dynamic_single_vm.ts
      - name: Run test kvstore 
        id: kvstore
        continue-on-error: true
        run: |
          yarn run ts-node --project tsconfig-node.json scripts/kvstore_example.ts
      - name: Run test zdb
        id: zdb
        continue-on-error: true
        run: |
          yarn run ts-node --project tsconfig-node.json scripts/zdb.ts
      - name: Cleanup - Delete all contracts
        run: |
          yarn run ts-node --project tsconfig-node.json scripts/delete_all_contracts.ts
      - name: Check test script status
        if: steps.singlevm.outcome != 'success' || steps.multiplevm.outcome != 'success' || steps.kubernetes.outcome != 'success' || steps.vmqsfs.outcome != 'success' || steps.kubernetesqsfs.outcome != 'success' || steps.dynamicsinglevm.outcome != 'success' || steps.kvstore.outcome != 'success' || steps.zdb.outcome != 'success'
        run: exit "Test scripts failed, Please check the failed step/s."